### ISSUE TITLE
Implement Server Status Screen on App Launch

### ISSUE THREAD

**Issue by chandansgowda** [AOSSIE-Org/Resonate#219]
### 🚀 The feature

When the app is launched, users should be presented with a screen indicating the server's status. This is crucial for transparency and user experience in case the server is down or undergoing maintenance.

### Proposed Solution

Implement a dedicated screen that can display relevant information about the server status. This screen should be shown when the app is launched and communicate whether the server is operational, undergoing maintenance, or facing issues.

### Tasks
 
- [ ] Design the server status screen with appropriate visual elements.
- [ ] Integrate logic to check the server status upon app launch.
- [ ]  Implement communication between the app and the server for status updates.
- [ ] Handle different scenarios (e.g., server operational, under maintenance, server down)
- [ ] Provide a mechanism for users to refresh or get more details if needed.

**Comment by I-MirzaBaig** [comment]
Can you explain more precisely?

**Comment by chandansgowda** [comment]
@I-MirzaBaig We are using appwrite for the backend and we'll never know when will appwrite be down. So if its down, then we wont be able to continue with the app's actual functionality. So, we need a screen to alert user that the server is down or under maintenance.

**Comment by SimardeepSingh1450** [comment]
@chandansgowda if there is no progress till now by @I-MirzaBaig then I would like to take up this issue.

**Comment by I-MirzaBaig** [comment]
@SimardeepSingh1450 You may go ahead with this issue, I'm not able to get accurate results until now. 

It's better I should give up.

**Comment by Jhalakupadhyay** [comment]
@chandansgowda can you take a look at https://github.com/AOSSIE-Org/Resonate/issues/211#issuecomment-1872820978 if you have any suggestion then I will like to proceed further with this issue and will automatically solve the issue that I have mentioned

**Comment by SimardeepSingh1450** [comment]
@Jhalakupadhyay , currently this issue is under disucssion, I would suggest please checkout other issues as this one is currently already under work.

**Comment by Jhalakupadhyay** [comment]
@SimardeepSingh1450  is the implementation has been resolved ? If not I would like to work upon this.

**Comment by Aarush-Acharya** [comment]
Hey thank you so much, for your sincere contributions to the project. Unfortunately though as we are moving towards a whole new revised version of Resonate. We would have to start fresh with the issues as in the new version of UI and some new features under development a lot has changes. Once the new version is out we will start accepting issues again and sprint through them including implementing merging pushing Resonate to even newer heights

**Comment by MiirzaBaig** [comment]
@Aarush-Acharya Your welcome,May i know how long newer versions comes in play?

**Comment by Aarush-Acharya** [comment]
hey @MiirzaBaig, newer version is expected to be fully complete by the end of the month 

But we are gladly accepting engagement regarding bug fixes and improvements in the current state of the app

New issues are being opened regarding so you can stay tuned or even pitch in a new issue for quality improvement or so
